test:
  stage: test
  image: eclipse-temurin:8
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  script:
    - ./gradlew check shadowJar
  artifacts:
    expire_in: 1 week
    paths:
      - build/libs/b-language-server-all.jar
    reports:
      junit:
        - "build/test-results/**/TEST-*.xml"
  cache:
    paths:
      - .gradle/caches
      - .gradle/native
      - .gradle/wrapper

trigger_extension_build:
  stage: .post
  trigger:
    project: general/stups/b_language_extension
    forward:
      yaml_variables: false
  only:
    - master@general/stups/b_language_server
