test:
  stage: test
  image: eclipse-temurin:8
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  script:
    - ./gradlew check shadowJar
  artifacts:
    expire_in: 1 week
    paths:
      - build/libs/b-language-server-all.jar
    reports:
      junit:
        - "build/test-results/**/TEST-*.xml"
  cache:
    paths:
      - .gradle/caches
      - .gradle/native
      - .gradle/wrapper

trigger_extension_build:
  stage: .post
  image: alpine:3
  dependencies: []
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk add --update curl
  script:
    - curl -X POST -F "token=$CI_JOB_TOKEN" -F "ref=main" https://gitlab.cs.uni-duesseldorf.de/api/v4/projects/2835/trigger/pipeline
  only:
    - master@general/stups/b_language_server
